### ISSUE TITLE
Global default path is wrong

### ISSUE THREAD

**Issue by twifty** [hash-bang/require-grep#1]
Just tried running your conkie module, only to find it cannot find a theme. Digging a little into the problem, `requireGrep` doesn't return the theme module path.

I see the problem lies within this module and its default `globalPaths` value of '/usr/lib/node_modules' which doesn't exist on my system.

While that value is fine for a fresh install of node, it is often changed, especially on linux systems, to avoid having to use sudo with `npm install -g`. Also, that value will not work on windows systems.

The correct value should come from `require('module').globalPaths`. This value should be appended with the result of `npm prefix -g` + 'lib/node_modules' or just 'node_modules' if on windows.

In my case `require('module').globalPaths`:
```js
[
  '/home/twifty/.node_modules', // Doesn't exist
  '/home/twifty/.node_libraries', // Doesn't exist
  '/usr/local/lib/node' // Owned by root
]
```
and `npm prefix -g`:
```js
'/home/twifty/npm' // This is where all my global npm installs are located
```

**Comment by hash-bang** [comment]
@twifty you are right. Can't believe I left that in.

I've patched the code and bumped the NPM packages + version of [Conkie](https://github.com/hash-bang/Conkie).

Can you give it another go and reopen if you're still having issues?

**Comment by twifty** [comment]
Still, this only works if using `sudo npm install -g` and if npm **hasn't** been configured with a prefix.

Like I mentioned above, my global npm installs to my `/home` directory. Your module is now only searching the root owned global directories. Even specifying the path the theme fails.

> twifty@twifty-lynx:\~$ conkie --background \~/npm/lib/node_modules/conkie-theme-default/index.html 
> twifty@twifty-lynx:\~$ [Conkie] ERR No theme file or matching module found

**Comment by hash-bang** [comment]
Grr. Sorry about this.

Ok. I've sat down with the NPM documentation and rigged up a quick test environment and I think its now working.

Can you give it a test on your setup and let me know if its ok for you?

**Comment by twifty** [comment]
I can confirm the latest fix now works.

**Comment by hash-bang** [comment]
Great stuff. Thanks for being so patient.
